# Generated by Django 6.0 on 2025-12-18 00:22

import django.db.models.deletion
import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao_curta', models.CharField(max_length=200)),
                ('descricao_detalhada', models.TextField()),
                ('tecnologias', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('imagem_principal', models.ImageField(upload_to=portfolio.models.upload_imagem_principal)),
            ],
        ),
        migrations.CreateModel(
            name='ImagemProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=portfolio.models.upload_imagem_secundaria)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='portfolio.projeto')),
            ],
        ),
    ]
